###
put http://localhost:3000/plateau/UpdatePlateau
content-type: application/json

{
   "plateauId":2,
    "idManager":10,
    "numberOfParties":3
}

###
post http://localhost:3000/auth/UpdatePlateau
content-type: application/json

{
   "plateauId":2,
    "idManager":10,
    "numberOfParties":3
}